#!/bin/bash
#SBATCH --job-name=SLIT_Mafft
#SBATCH --nodes=1                 
#SBATCH --ntasks=1               
#SBATCH --cpus-per-task=32      
#SBATCH --mem=32G                 
#SBATCH --output=/rna/liha/phylogenomics_practice/SLIT2/logs/mafft_%j.log    
#SBATCH --error=/rna/liha/phylogenomics_practice/SLIT2/logs/mafft_%j.log      

source ~/miniconda3/etc/profile.d/conda.sh 
conda activate alignments 

echo "Job started on $(hostname) at $(date)" 

# 1. Set paths for the FASTA generated by the previous Python step.
BASE_DIR="/rna/liha/phylogenomics_practice/SLIT2"
INPUT_FILE="${BASE_DIR}/Scripts/SLIT-homologs.fasta"

# Define where the aligned FASTA will be saved.
OUTPUT_DIR="${BASE_DIR}/Alignments"
OUTPUT_FILE="${OUTPUT_DIR}/SLIT_aligned.fasta"

# 2. Create the output directory if it does not exist.
mkdir -p "$OUTPUT_DIR"

echo "Starting SLIT alignment with MAFFT --localpair..." 

# 3. Run MAFFT on the single input FASTA.
if [ -f "$INPUT_FILE" ]; then
    echo "Processing SLIT sequences..."
    
    # Use the L-INS-i strategy (--localpair) with the SLURM-allocated CPU count.
    mafft --localpair --maxiterate 1000 --thread $SLURM_CPUS_PER_TASK "$INPUT_FILE" > "$OUTPUT_FILE"
    
    echo "Alignment complete. Output: $OUTPUT_FILE"
else
    echo "Error: input file not found: $INPUT_FILE"
    exit 1
fi

echo "Job ended at $(date)"